# Generated by Django 5.2.7 on 2025-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_store', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
